/**
 * image.ts — T031, T064, T065, T066
 *
 * Utilities for generating accessible, performant image markup.
 * - Generates <picture> HTML strings with WebP + JPEG/PNG sources
 * - Handles responsive srcset at three breakpoints
 * - Enforces lazy loading for below-fold images
 * - Enforces eager loading + width/height for above-fold images (CLS prevention)
 */

export interface ImageOptions {
  /** Path relative to /public (e.g. "/images/projects/my-project") — without extension */
  src: string;
  /** Descriptive alt text (required, 1–120 chars). Pass "" for decorative images. */
  alt: string;
  /** Intrinsic pixel width of the original image */
  width: number;
  /** Intrinsic pixel height of the original image */
  height: number;
  /**
   * Loading strategy.
   * - "lazy"  → below-fold images (default)
   * - "eager" → above-fold / hero images (LCP candidates)
   */
  loading?: 'lazy' | 'eager';
  /** Additional CSS class names applied to <img> */
  className?: string;
  /**
   * Responsive size hint for the browser (CSS value).
   * Defaults to "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw"
   */
  sizes?: string;
}

/** Widths generated by the optimize-images script for each asset */
const SRCSET_WIDTHS = [400, 800, 1200] as const;

const DEFAULT_SIZES = '(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw';

/**
 * Returns the <img> srcset attribute string for a given image base path and format.
 *
 * Assumes the optimize-images script has generated:
 *   /images/projects/my-project-400w.webp
 *   /images/projects/my-project-800w.webp
 *   /images/projects/my-project-1200w.webp
 *   (and equivalent .jpg files)
 */
export function buildSrcSet(basePath: string, ext: 'webp' | 'jpg'): string {
  return SRCSET_WIDTHS.map((w) => `${basePath}-${w}w.${ext} ${w}w`).join(', ');
}

/**
 * Returns an object with the properties required to render an optimised <picture>
 * element. Intended for use in Astro components (spread into a picture helper).
 *
 * For React components, use the `OptimizedImage` component instead.
 */
export function getImageProps(options: ImageOptions): {
  webpSrcSet: string;
  jpegSrcSet: string;
  fallbackSrc: string;
  alt: string;
  width: number;
  height: number;
  loading: 'lazy' | 'eager';
  decoding: 'async' | 'sync';
  sizes: string;
  className?: string;
} {
  const { src, alt, width, height, loading = 'lazy', className, sizes = DEFAULT_SIZES } = options;

  return {
    webpSrcSet: buildSrcSet(src, 'webp'),
    jpegSrcSet: buildSrcSet(src, 'jpg'),
    fallbackSrc: `${src}-800w.jpg`,
    alt,
    width,
    height,
    loading,
    decoding: loading === 'eager' ? 'sync' : 'async',
    sizes,
    ...(className ? { className } : {}),
  };
}

/**
 * Determines whether an image should use eager loading.
 * Above-fold images (hero background, first 3 project thumbnails) use eager loading
 * to avoid penalising LCP.
 */
export function isAboveFold(index: number): boolean {
  return index < 3;
}

/**
 * Returns the preload link attributes for a critical image.
 * Add to <head> via BaseLayout for above-fold images.
 *
 * @example
 * const preload = getPreloadLinkAttrs('/images/hero-bg/hero', 'webp');
 * // → { rel: 'preload', as: 'image', href: '...', imageSrcset: '...' }
 */
export function getPreloadLinkAttrs(
  basePath: string,
  format: 'webp' | 'jpg' = 'webp',
  sizes: string = DEFAULT_SIZES,
): {
  rel: 'preload';
  as: 'image';
  href: string;
  imageSrcset: string;
  imagesizes: string;
  type: string;
} {
  return {
    rel: 'preload',
    as: 'image',
    href: `${basePath}-800w.${format}`,
    imageSrcset: buildSrcSet(basePath, format),
    imagesizes: sizes,
    type: format === 'webp' ? 'image/webp' : 'image/jpeg',
  };
}
